=== api-evangelist/apache-dubbo/json-schema/dubbo-admin-model.-consumer-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/apache-dubbo/refs/heads/main/json-schema/dubbo-admin-model.-consumer-schema.json",
  "title": "model.Consumer",
  "description": "model.Consumer schema from Dubbo Admin API",
  "type": "object",
  "properties": {
    "address": {
      "type": "string"
    },
    "alived": {
      "type": "integer"
    },
    "application": {
      "type": "string"
    },
    "collected": {
      "$ref": "#/definitions/time.Duration"
    },
    "created": {
      "type": "string"
    },
    "expired": {
      "$ref": "#/definitions/time.Duration"
    },
    "hash": {
      "type": "string"
    },
    "id": {
      "type": "integer"
    },
    "ids": {
      "type": "array",
      "items": {
        "type": "integer"
      }
    },
    "miss": {
      "type": "boolean"
    },
    "modified": {
      "type": "string"
    },
    "now": {
      "type": "string"
    },
    "operator": {
      "type": "string"
    },
    "operatorAddress": {
      "type": "string"
    },
    "parameters": {
      "type": "string"
    },
    "registry": {
      "type": "string"
    },
    "result": {
      "type": "string"
    },
    "service": {
      "type": "string"
    },
    "statistics": {
      "type": "string"
    },
    "username": {
      "type": "string"
    }
  }
}

=== api-evangelist/apache-dubbo/examples/dubbo-admin-model.-consumer-example.json
{
  "address": "10.0.0.1:20880",
  "alived": 1,
  "application": "my-dubbo-app",
  "collected": "example-value",
  "created": "example-value",
  "expired": "example-value",
  "hash": "example-value",
  "id": 1,
  "ids": [
    1
  ],
  "miss": true,
  "modified": "example-value",
  "now": "example-value",
  "operator": "example-value",
  "operatorAddress": "10.0.0.1:20880",
  "parameters": "example-value",
  "registry": "example-value",
  "result": "example-value",
  "service": "com.example.DemoService",
  "statistics": "example-value",
  "username": "example-service"
}
