=== api-evangelist/apache-dubbo/json-schema/dubbo-admin-model.-condition-route-dto-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/apache-dubbo/refs/heads/main/json-schema/dubbo-admin-model.-condition-route-dto-schema.json",
  "title": "model.ConditionRouteDto",
  "description": "model.ConditionRouteDto schema from Dubbo Admin API",
  "type": "object",
  "properties": {
    "application": {
      "type": "string"
    },
    "conditions": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "configVersion": {
      "type": "string"
    },
    "enabled": {
      "type": "boolean"
    },
    "force": {
      "type": "boolean"
    },
    "id": {
      "type": "string"
    },
    "priority": {
      "type": "integer"
    },
    "runtime": {
      "type": "boolean"
    },
    "service": {
      "type": "string"
    },
    "serviceGroup": {
      "type": "string"
    },
    "serviceVersion": {
      "type": "string"
    }
  },
  "required": [
    "conditions",
    "configVersion",
    "enabled"
  ]
}

=== api-evangelist/apache-dubbo/examples/dubbo-admin-model.-condition-route-dto-example.json
{
  "application": "my-dubbo-app",
  "conditions": [
    "example-value"
  ],
  "configVersion": "1.0.0",
  "enabled": true,
  "force": true,
  "id": "500123",
  "priority": 1,
  "runtime": true,
  "service": "com.example.DemoService",
  "serviceGroup": "com.example.DemoService",
  "serviceVersion": "1.0.0"
}
