=== api-evangelist/apache-dubbo/json-schema/dubbo-admin-model.-provider-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/apache-dubbo/refs/heads/main/json-schema/dubbo-admin-model.-provider-schema.json",
  "title": "model.Provider",
  "description": "model.Provider schema from Dubbo Admin API",
  "type": "object",
  "properties": {
    "address": {
      "type": "string"
    },
    "alived": {
      "type": "integer"
    },
    "application": {
      "type": "string"
    },
    "created": {
      "type": "string"
    },
    "dynamic": {
      "type": "boolean"
    },
    "enabled": {
      "type": "boolean"
    },
    "expired": {
      "$ref": "#/definitions/time.Duration"
    },
    "hash": {
      "type": "string"
    },
    "id": {
      "type": "integer"
    },
    "ids": {
      "type": "array",
      "items": {
        "type": "integer"
      }
    },
    "miss": {
      "type": "boolean"
    },
    "modified": {
      "type": "string"
    },
    "now": {
      "type": "string"
    },
    "operator": {
      "type": "string"
    },
    "operatorAddress": {
      "type": "string"
    },
    "parameters": {
      "type": "string"
    },
    "registry": {
      "type": "string"
    },
    "registrySource": {
      "$ref": "#/definitions/model.RegistrySource"
    },
    "serialization": {
      "type": "string"
    },
    "service": {
      "type": "string"
    },
    "timeout": {
      "type": "integer"
    },
    "url": {
      "type": "string"
    },
    "username": {
      "type": "string"
    },
    "weight": {
      "type": "integer"
    }
  }
}

=== api-evangelist/apache-dubbo/examples/dubbo-admin-model.-provider-example.json
{
  "address": "10.0.0.1:20880",
  "alived": 1,
  "application": "my-dubbo-app",
  "created": "example-value",
  "dynamic": true,
  "enabled": true,
  "expired": "example-value",
  "hash": "example-value",
  "id": 1,
  "ids": [
    1
  ],
  "miss": true,
  "modified": "example-value",
  "now": "example-value",
  "operator": "example-value",
  "operatorAddress": "10.0.0.1:20880",
  "parameters": "example-value",
  "registry": "example-value",
  "registrySource": "example-value",
  "serialization": "example-value",
  "service": "com.example.DemoService",
  "timeout": 1,
  "url": "https://example.com",
  "username": "example-service",
  "weight": 1
}
